steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/$_APP', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/$_APP']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['beta', 'run', 'deploy', '$_APP-$_DEPLOY_REGION', '--image', 'gcr.io/$PROJECT_ID/$_APP', '--region', '$_DEPLOY_REGION', '--platform', 'managed']
images:
- gcr.io/$PROJECT_ID/$_APP
substitutions:
    _APP: flynn-hubauth
    _DEPLOY_REGION: us-central-1
