steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/$_APP', '.']
- name: 'gcr.io/cloud-builders/docker'
  id: push
  args: ['push', 'gcr.io/$PROJECT_ID/$_APP']
- name: 'gcr.io/cloud-builders/gcloud'
  waitFor: ['push']
  args: ['beta', 'run', 'deploy', '$_APP-ext-$_DEPLOY_REGION_PRIMARY', '--image', 'gcr.io/$PROJECT_ID/$_APP', '--region', '$_DEPLOY_REGION_PRIMARY', '--platform', 'managed']
- name: 'gcr.io/cloud-builders/gcloud'
  waitFor: ['push']
  args: ['beta', 'run', 'deploy', '$_APP-ext-$_DEPLOY_REGION_FALLBACK', '--image', 'gcr.io/$PROJECT_ID/$_APP', '--region', '$_DEPLOY_REGION_FALLBACK', '--platform', 'managed']
- name: 'gcr.io/cloud-builders/gcloud'
  waitFor: ['push']
  args: ['beta', 'run', 'deploy', '$_APP-int-$_DEPLOY_REGION_PRIMARY', '--image', 'gcr.io/$PROJECT_ID/$_APP', '--region', '$_DEPLOY_REGION_PRIMARY', '--platform', 'managed']
images:
- gcr.io/$PROJECT_ID/$_APP
substitutions:
    _APP: hubauth
    _DEPLOY_REGION_PRIMARY: us-central1
    _DEPLOY_REGION_FALLBACK: us-west1
