steps:
- name: 'gcr.io/kaniko-project/executor'
  id: build
  args: [
    '--dockerfile=Dockerfile',
    '--context=.',
    '--destination=gcr.io/$PROJECT_ID/$_APP:latest',
  ]
- name: 'gcr.io/cloud-builders/gcloud'
  waitFor: ['build']
  args: [
    'beta', 'run', 'deploy',
    '$_APP-ext-$_DEPLOY_REGION_PRIMARY',
    '--platform', 'managed',
    '--image', 'gcr.io/$PROJECT_ID/$_APP',
    '--region', '$_DEPLOY_REGION_PRIMARY',
    '--update-env-vars', 'BUILD_REPO=$REPO_NAME,BUILD_REV=$COMMIT_SHA',
  ]
- name: 'gcr.io/cloud-builders/gcloud'
  waitFor: ['build']
  args: [
    'beta', 'run', 'deploy',
    '$_APP-ext-$_DEPLOY_REGION_FALLBACK',
    '--platform', 'managed',
    '--image', 'gcr.io/$PROJECT_ID/$_APP',
    '--region', '$_DEPLOY_REGION_FALLBACK',
    '--update-env-vars', 'BUILD_REPO=$REPO_NAME,BUILD_REV=$COMMIT_SHA',
  ]
- name: 'gcr.io/cloud-builders/gcloud'
  waitFor: ['build']
  args: [
    'beta', 'run', 'deploy',
    '$_APP-int-$_DEPLOY_REGION_PRIMARY',
    '--platform', 'managed',
    '--image', 'gcr.io/$PROJECT_ID/$_APP',
    '--region', '$_DEPLOY_REGION_PRIMARY',
    '--update-env-vars', 'BUILD_REPO=$REPO_NAME,BUILD_REV=$COMMIT_SHA',
  ]
images:
- gcr.io/$PROJECT_ID/$_APP
substitutions:
    _APP: hubauth
    _DEPLOY_REGION_PRIMARY: us-central1
    _DEPLOY_REGION_FALLBACK: us-west1
