name: CI

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build test environment
        run: docker build --file test.Dockerfile --tag hubauth-test .
      - name: Run tests
        run: docker run hubauth-test
